version: "3.7"
services:

  # core:
  #   build: ./core
  #   depends_on:
  #   env_file: .env

  auth:
    build: ./auth
    depends_on:
      - app-db
    ports:
      - "8080:8080"
      - "3000:3000"
    environment:
      - DB_HOST=app-db
      - DB_PASSWORD=${DB_APP_PASSWORD}
      - HYDRA_ADMIN_URL=http://hydra:4445
      - HYDRA_PUBLIC_URL=http://hydra:4444
    restart: unless-stopped

  telegram:
    build: ./telegram
    env_file:
      - ./secret.env
    depends_on:
      - auth
    restart: unless-stopped

  app-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_APP_PASSWORD}
    volumes:
      - "data-app:/var/lib/postgresql/data"
    restart: unless-stopped

  hydra:
    image: oryd/hydra:latest
    depends_on:
      - hydra-migrate
    command:
      serve all --dangerous-force-http
    ports: 
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Example port
    environment:
      - DSN=postgres://postgres:${DB_HYDRA_PASSWORD}@hydra-db:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4
      - URLS_SELF_ISSUER=http://127.0.0.1:4444
      - URLS_CONSENT=http://127.0.0.1:8080/consent
      - URLS_LOGIN=http://127.0.0.1:8080/login
      - SECRETS_SYSTEM=verySecretMuchSecure
    restart: unless-stopped

  hydra-migrate:
    image: oryd/hydra:latest
    depends_on:
      - hydra-db
    environment:
      - DSN=postgres://postgres:${DB_HYDRA_PASSWORD}@hydra-db:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4
    command:
      migrate sql -e --yes
    restart: on-failure

  hydra-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_HYDRA_PASSWORD}
    volumes:
      - "data-hydra:/var/lib/postgresql/data"
    restart: unless-stopped

volumes:
  data-hydra:
  data-app: